name: Run Test plugin
on: [pull_request]

jobs:
  tag:
    name: PHP ${{ matrix.php }} / WP ${{ matrix.wp }} Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        include:
          - php: 7.4
            wp: trunk
            experimental: true
          - php: 8.0
            wp: trunk
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: PHP ${{ matrix.php }} / WP ${{ matrix.wp }} Test
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl , mysqli
          ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
          coverage: xdebug #optional, setup coverage driver

      - name: Check PHP Version
        run: php -v

      - name: Cache composer packages
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: composer update
        run: composer update

      - name: composer install
        run: composer install --optimize-autoloader --prefer-dist

      - name: Coding Style check
        run: composer lint

      - name: Code Analyze
        run: composer analyze

      - name: Install WP Tests
        run: bash tests/phpunit/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wp }} true false

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          mv wp-cli.phar /usr/local/bin/wp
      - name: Check Install WP-CLI
        run: |
          wp --version
      - name: Configure WordPress
        run: >
          wp config create
          --allow-root
          --dbname=wordpress_test
          --dbuser=root
          --dbpass=root
          --dbhost=127.0.0.1
          --locale=ja
          --force
        working-directory: /tmp/wordpress

      - name: Install WordPress
        run: >
          wp core install
          --allow-root
          --url=localhost
          --title=WP
          --admin_user=admin
          --admin_email=admin@example.com
          --admin_password=password
          --skip-email
        working-directory: /tmp/wordpress

      - name: phpunit tests
        run: |
          vendor/bin/phpunit -c tests/phpunit/phpunit.xml.dist
